"""
PDF to Web converter

Warm-up task for the hackathon. Takes a PDF and turns it into a webpage.
Usage: python pdf_to_web.py input.pdf output.html
"""
import sys
import os
import asyncio
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from core.paddleocr_client import PaddleOCRClient
from core.ernie_client import ERNIEClient


async def pdf_to_webpage(pdf_path: str, output_path: str = None) -> str:
    """
    Convert PDF to webpage.
    
    Args:
        pdf_path: Path to PDF file
        output_path: Output HTML file path (optional)
        
    Returns:
        Generated HTML content
    """
    print(f"Processing PDF: {pdf_path}")
    
    print("Step 1: Extracting text with PaddleOCR-VL...")
    ocr_client = PaddleOCRClient()
    ocr_result = ocr_client.extract_from_pdf(pdf_path)
    
    print("Step 2: Converting to Markdown format...")
    markdown_content = ocr_client.to_markdown(ocr_result)
    
    print(f"   Extracted {ocr_result['page_count']} pages")
    print(f"   Text length: {len(markdown_content)} characters")
    
    print("Step 3: Generating webpage with ERNIE...")
    ernie_client = ERNIEClient()
    html_content = await ernie_client.generate_html(markdown_content)
    
    if output_path:
        output_file = Path(output_path)
    else:
        output_file = Path(pdf_path).with_suffix('.html')
    
    # Clean up any remaining markdown code blocks
    html_content = html_content.strip()
    if html_content.startswith("```"):
        lines = html_content.split('\n')
        lines = lines[1:]  # Remove first line with ```html
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]  # Remove last line with ```
        html_content = '\n'.join(lines)
    
    # Wrap if not complete HTML
    if not html_content.strip().startswith('<!DOCTYPE') and not html_content.strip().startswith('<html'):
        html_content = wrap_html(html_content, Path(pdf_path).stem)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"Webpage generated: {output_file}")
    
    return html_content


def wrap_html(content: str, title: str = "Document") -> str:
    """Wrap content in complete HTML structure."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.8;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px 20px;
            background: #f5f5f5;
        }}
        .container {{
            background: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1, h2, h3 {{
            color: #1a1a1a;
            margin: 1.5em 0 0.5em;
        }}
        h1 {{
            font-size: 2em;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 10px;
        }}
        p {{
            margin: 1em 0;
        }}
        pre {{
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            overflow-x: auto;
        }}
        .footer {{
            text-align: center;
            margin-top: 40px;
            color: #666;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="container">
        {content}
    </div>
    <div class="footer">
        <p>Generated by DocuMind | ERNIE & PaddlePaddle Hackathon 2025</p>
    </div>
</body>
</html>"""


async def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: python pdf_to_web.py <pdf_file> [output_html]")
        print("Example: python pdf_to_web.py document.pdf output.html")
        sys.exit(1)
    
    pdf_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else None
    
    if not os.path.exists(pdf_path):
        print(f"Error: File not found - {pdf_path}")
        sys.exit(1)
    
    await pdf_to_webpage(pdf_path, output_path)


if __name__ == "__main__":
    asyncio.run(main())
